
import { TranslationStrings, CardData, Language } from './types';

export const LANGUAGES_CONFIG: Record<Language, { name: string, native: string, dir: 'rtl' | 'ltr', flag: string }> = {
  ar: { name: 'Arabic', native: 'العربية', dir: 'rtl', flag: '🇸🇦' },
  en: { name: 'English', native: 'English', dir: 'ltr', flag: '🇺🇸' },
} as any;

export const AVAILABLE_FONTS = [
  { id: 'Cairo', name: 'Cairo (Modern)', nameAr: 'خط كاييرو (عصري)' },
  { id: 'Almarai', name: 'Almarai', nameAr: 'خط المراعي' },
  { id: 'Tajawal', name: 'Tajawal', nameAr: 'خط تجول' },
  { id: 'IBM Plex Sans Arabic', name: 'IBM Plex Sans', nameAr: 'خط آي بي إم' },
  { id: 'Vazirmatn', name: 'Vazirmatn', nameAr: 'خط وزير متن' },
  { id: 'Noto Sans Arabic', name: 'Noto Sans', nameAr: 'خط نوتو سانز' },
  { id: 'Amiri', name: 'Amiri (Classic)', nameAr: 'خط أميري (كلاسيك)' },
  { id: 'Lalezar', name: 'Lalezar (Bold)', nameAr: 'خط لاليزار (عريض)' },
  { id: 'Changa', name: 'Changa', nameAr: 'خط تشانغا' },
  { id: 'Lemonada', name: 'Lemonada', nameAr: 'خط ليمونادا' },
  { id: 'Montserrat', name: 'Montserrat', nameAr: 'خط مونتيسرات' },
  { id: 'Roboto', name: 'Roboto', nameAr: 'خط روبوتو' }
];

export const THEME_COLORS = [
  '#2563eb', '#1e40af', '#3b82f6', '#0ea5e9', '#06b6d4', 
  '#14b8a6', '#10b981', '#22c55e', '#84cc16', 
  '#eab308', '#f97316', '#ef4444', '#f43f5e', '#db2777', 
  '#d946ef', '#a855f7', '#7c3aed', '#6366f1', 
  '#4b5563', '#1e293b', '#0f172a', '#000000',
  '#FF6B6B', '#4ECDC4', '#45B7D1', '#96CEB4', '#FFEEAD',
  '#D4AF37', '#C0C0C0', '#8E44AD', '#2C3E50', '#E67E22'
];

export const THEME_GRADIENTS = [
  'linear-gradient(135deg, #3b82f6 0%, #2563eb 100%)',
  'linear-gradient(135deg, #6366f1 0%, #4f46e5 100%)',
  'linear-gradient(135deg, #a855f7 0%, #7c3aed 100%)',
  'linear-gradient(135deg, #ec4899 0%, #db2777 100%)',
  'linear-gradient(135deg, #f43f5e 0%, #e11d48 100%)',
  'linear-gradient(135deg, #f97316 0%, #ea580c 100%)',
  'linear-gradient(135deg, #10b981 0%, #059669 100%)',
  'linear-gradient(135deg, #06b6d4 0%, #0891b2 100%)',
  'linear-gradient(135deg, #1e293b 0%, #0f172a 100%)',
  'linear-gradient(to right, #ffecd2 0%, #fcb69f 100%)',
  'linear-gradient(to right, #ff9a9e 0%, #fecfef 99%, #fecfef 100%)',
  'linear-gradient(120deg, #a1c4fd 0%, #c2e9fb 100%)',
  'linear-gradient(to top, #cfd9df 0%, #e2ebf0 100%)',
  'linear-gradient(to right, #4facfe 0%, #00f2fe 100%)',
  'linear-gradient(to right, #434343 0%, #000000 100%)',
  'linear-gradient(45deg, #8baaaa 0%, #ae8b9c 100%)',
  'linear-gradient(to right, #6a11cb 0%, #2575fc 100%)',
  'linear-gradient(to right, #b8cbb8 0%, #b8cbb8 0%, #b465da 0%, #cf6cc9 33%, #ee609c 66%, #ee609c 100%)'
];

export const SOCIAL_PLATFORMS = [
  { id: 'linkedin', name: 'LinkedIn' },
  { id: 'x', name: 'X (Twitter)' },
  { id: 'facebook', name: 'Facebook' },
  { id: 'instagram', name: 'Instagram' },
  { id: 'whatsapp_social', name: 'WhatsApp' },
  { id: 'telegram', name: 'Telegram' },
  { id: 'snapchat', name: 'Snapchat' },
  { id: 'tiktok', name: 'TikTok' },
  { id: 'threads', name: 'Threads' },
  { id: 'youtube', name: 'YouTube' },
  { id: 'github', name: 'GitHub' },
  { id: 'behance', name: 'Behance' },
  { id: 'dribbble', name: 'Dribbble' },
  { id: 'pinterest', name: 'Pinterest' },
  { id: 'discord', name: 'Discord' },
  { id: 'twitch', name: 'Twitch' },
  { id: 'spotify', name: 'Spotify' }
];

export const BACKGROUND_PRESETS = [
  'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&q=80&w=800',
  'https://images.unsplash.com/photo-1557682250-33bd709cbe85?auto=format&fit=crop&q=80&w=800',
  'https://images.unsplash.com/photo-1620641788421-7a1c342ea42e?auto=format&fit=crop&q=80&w=800',
  'https://images.unsplash.com/photo-1634017839464-5c339ebe3cb4?auto=format&fit=crop&q=80&w=800',
  'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&q=80&w=800',
  'https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&q=80&w=800',
  'https://images.unsplash.com/photo-1517502884422-41eaead166d4?auto=format&fit=crop&q=80&w=800',
  'https://images.unsplash.com/photo-1513151233558-d860c5398176?auto=format&fit=crop&q=80&w=800',
  'https://images.unsplash.com/photo-1498931299472-f7a63a5a1cfa?auto=format&fit=crop&q=80&w=800',
  'https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3?auto=format&fit=crop&q=80&w=800',
  'https://images.unsplash.com/photo-1549465220-1a8b9238cd48?auto=format&fit=crop&q=80&w=800',
  'https://images.unsplash.com/photo-1513519245088-0e12902e5a38?auto=format&fit=crop&q=80&w=800',
  'https://images.unsplash.com/photo-1470071459604-3b5ec3a7fe05?auto=format&fit=crop&q=80&w=800',
  'https://images.unsplash.com/photo-1501854140801-50d01698950b?auto=format&fit=crop&q=80&w=800',
  'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&q=80&w=800',
  'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?auto=format&fit=crop&q=80&w=800',
  'https://images.unsplash.com/photo-1533158326339-7f3cf2404354?auto=format&fit=crop&q=80&w=800',
  'https://images.unsplash.com/photo-1518640467707-6811f4a6ab73?auto=format&fit=crop&q=80&w=800',
  'https://images.unsplash.com/photo-1536924940846-227afb31e2a5?auto=format&fit=crop&q=80&w=800',
  'https://images.unsplash.com/photo-1504333638930-c8787321eee0?auto=format&fit=crop&q=80&w=800'
];

export const AVATAR_PRESETS = [
  'https://api.dicebear.com/7.x/avataaars/svg?seed=Felix',
  'https://api.dicebear.com/7.x/avataaars/svg?seed=Aneka',
  'https://api.dicebear.com/7.x/avataaars/svg?seed=Sasha',
  'https://api.dicebear.com/7.x/avataaars/svg?seed=Midnight',
  'https://api.dicebear.com/7.x/bottts/svg?seed=Robo1',
  'https://api.dicebear.com/7.x/bottts/svg?seed=Robo2',
  'https://api.dicebear.com/7.x/fun-emoji/svg?seed=Happy',
  'https://api.dicebear.com/7.x/fun-emoji/svg?seed=Cool',
  'https://api.dicebear.com/7.x/fun-emoji/svg?seed=Love',
  'https://api.dicebear.com/7.x/notionists/svg?seed=Work1',
  'https://api.dicebear.com/7.x/notionists/svg?seed=Work2',
  'https://api.dicebear.com/7.x/notionists/svg?seed=Work3',
  'https://api.dicebear.com/7.x/pixel-art/svg?seed=Player1',
  'https://api.dicebear.com/7.x/pixel-art/svg?seed=Player2',
  'https://api.dicebear.com/7.x/micah/svg?seed=M1',
  'https://api.dicebear.com/7.x/micah/svg?seed=M2',
  'https://api.dicebear.com/7.x/miniavs/svg?seed=A1',
  'https://api.dicebear.com/7.x/miniavs/svg?seed=A2',
];

export const PATTERN_PRESETS = [
  { id: 'none', name: 'None', svg: '' },
  { id: 'dots', name: 'Dots', svg: '<svg width="20" height="20" viewBox="0 0 20 20"><circle cx="2" cy="2" r="1" fill="currentColor"/></svg>' },
  { id: 'grid', name: 'Grid', svg: '<svg width="20" height="20" viewBox="0 0 20 20"><path d="M 20 0 L 0 0 0 20" fill="none" stroke="currentColor" stroke-width="0.5"/></svg>' },
  { id: 'lines', name: 'Lines', svg: '<svg width="20" height="20" viewBox="0 0 20 20"><path d="M 0 10 L 20 10" fill="none" stroke="currentColor" stroke-width="0.5"/></svg>' },
  { id: 'cross', name: 'Cross', svg: '<svg width="20" height="20" viewBox="0 0 20 20"><path d="M 10 0 L 10 20 M 0 10 L 20 10" fill="none" stroke="currentColor" stroke-width="0.5"/></svg>' }
];

export const SVG_PRESETS = [
  { id: 'wave', name: 'Wave', icon: 'Waves' },
  { id: 'curve', name: 'Curve', icon: 'Wind' }
];

export const SAMPLE_DATA: Record<string, Partial<CardData>> = {
  en: {
    name: 'John Doe',
    title: 'Senior Software Engineer',
    company: 'Tech Innovations',
    bio: 'Passionate about building scalable web applications and exploring the latest AI technologies.',
    email: 'john.doe@example.com',
    phone: '+1 234 567 8900',
    whatsapp: '12345678900',
    website: 'https://johndoe.dev',
    emails: ['john.doe@example.com', 'work@johndoe.dev'],
    websites: ['https://johndoe.dev', 'https://github.com/johndoe'],
    isDark: false,
    themeType: 'gradient',
    themeGradient: THEME_GRADIENTS[0],
    socialLinks: [
      { platformId: 'linkedin', platform: 'LinkedIn', url: '#' },
      { platformId: 'x', platform: 'X', url: '#' },
      { platformId: 'instagram', platform: 'Instagram', url: '#' },
      { platformId: 'tiktok', platform: 'TikTok', url: '#' },
      { platformId: 'snapchat', platform: 'Snapchat', url: '#' },
      { platformId: 'whatsapp_social', platform: 'WhatsApp', url: '#' }
    ],
    specialLinks: [
      { id: '1', imageUrl: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&q=80&w=400', linkUrl: '#', titleEn: 'New Product' },
      { id: '2', imageUrl: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&q=80&w=400', linkUrl: '#', titleEn: 'Best Seller' }
    ]
  },
  ar: {
    name: 'أحمد محمد',
    title: 'مهندس برمجيات أول',
    company: 'ابتكارات التقنية',
    bio: 'شغوف ببناء تطبيقات الويب القابلة للتوسع واستكشاف أحدث تقنيات الذكاء الاصطناعي.',
    email: 'ahmed.m@example.com',
    phone: '+966 50 123 4567',
    whatsapp: '966501234567',
    website: 'https://ahmed@example.com',
    emails: ['ahmed.m@example.com'],
    websites: ['example.com'],
    isDark: false,
    themeType: 'gradient',
    themeGradient: THEME_GRADIENTS[0],
    socialLinks: [
      { platformId: 'linkedin', platform: 'LinkedIn', url: '#' },
      { platformId: 'x', platform: 'X', url: '#' },
      { platformId: 'instagram', platform: 'Instagram', url: '#' },
      { platformId: 'tiktok', platform: 'TikTok', url: '#' },
      { platformId: 'snapchat', platform: 'Snapchat', url: '#' },
      { platformId: 'whatsapp_social', platform: 'WhatsApp', url: '#' }
    ],
    specialLinks: [
      { id: '1', imageUrl: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&q=80&w=400', linkUrl: '#', titleAr: 'منتج جديد' },
      { id: '2', imageUrl: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&q=80&w=400', linkUrl: '#', titleAr: 'الأكثر مبيعاً' }
    ]
  }
};

export const TRANSLATIONS: TranslationStrings = {
  appName: { en: 'NextID', ar: 'هويتي' },
  home: { en: 'Home', ar: 'الرئيسية' },
  howToStart: { en: 'How to Start', ar: 'كيف تبدأ' },
  templates: { en: 'Templates', ar: 'القوالب' },
  myCards: { en: 'My Cards', ar: 'بطاقاتي' },
  admin: { en: 'Admin', ar: 'الإدارة' },
  account: { en: 'Account', ar: 'الحساب' },
  login: { en: 'Login / Register', ar: 'دخول / تسجيل' },
  loginOnly: { en: 'Login', ar: 'دخول' },
  registerOnly: { en: 'Register', ar: 'تسجيل جديد' },
  logout: { en: 'Logout', ar: 'خروج' },
  saveChanges: { en: 'Save Changes', ar: 'حفظ التعديلات' },
  fullName: { en: 'Full Name', ar: 'الاسم الكامل' },
  placeholderName: { en: 'Enter your name', ar: 'أدخل اسمك الكامل' },
  theme: { en: 'Theme', ar: 'السمة' },
  saveContact: { en: 'Save Contact', ar: 'حفظ جهة الاتصال' },
  call: { en: 'Call', ar: 'اتصال' },
  whatsappBtn: { en: 'WhatsApp', ar: 'واتساب' },
  heroBadge: { en: 'Create your digital identity', ar: 'أنشئ هويتك الرقمية الآن' },
  heroTitle: { en: 'Professional Digital Business Cards', ar: 'بطاقات أعمال رقمية احترافية' },
  heroDesc: { en: 'The easiest way to share your professional profile with the world.', ar: 'الطريقة الأسهل لمشاركة ملفك المهني مع العالم.' },
  createBtn: { en: 'Create Now', ar: 'ابدأ الآن' },
  template: { en: 'Layout Template', ar: 'قالب التوزيع' },
  selectTemplate: { en: 'Select Style', ar: 'اختر النمط الهيكلي' },
  bio: { en: 'Professional Bio', ar: 'النبذة المهنية' },
  email: { en: 'Email Address', ar: 'البريد الإلكتروني' },
  phone: { en: 'Phone Number', ar: 'رقم الهاتف' },
  whatsapp: { en: 'WhatsApp', ar: 'رقم الواتساب' },
  website: { en: 'Website URL', ar: 'رابط الموقع' },
  location: { en: 'Location Address', ar: 'عنوان الموقع' },
  locationUrl: { en: 'Google Maps Link', ar: 'رابط خريطة قوقل' },
  locationSection: { en: 'Geographical Location', ar: 'الموقع الجغرافي' },
  visitUs: { en: 'Visit Us', ar: 'تفضل بزيارتنا' },
  socials: { en: 'Social Links', ar: 'روابط التواصل' },
  jobTitle: { en: 'Job Title', ar: 'المسمى الوظيفي' },
  company: { en: 'Company', ar: 'الشركة' },
  templatesTitle: { en: 'Discover Our Templates', ar: 'اكتشف قوالبنا الاحترافية' },
  templatesDesc: { en: 'Choose the perfect design that reflects your professional identity.', ar: 'اختر التصميم المثالي الذي يعكس هويتك المهنية الراقية.' },
  useTemplate: { en: 'Use This Design', ar: 'استخدم هذا التصميم' },
  noCardsYet: { en: 'No cards yet', ar: 'لا توجد بطاقات حتى الآن' },
  supportProject: { en: 'Support this free project', ar: 'ادعم استمرارية هذا المشروع مجاناً' },
  buyMeCoffee: { en: 'Buy Me a Coffee', ar: 'تبرع بكوب قهوة' },
  supportProjectText: { 
    ar: 'تبرع بكوب قهوة ليسر الموقع مجاناً للأبد', 
    en: 'Donate a coffee to keep the site free forever' 
  },
  rightsReserved: { 
    ar: 'كافة الحقوق محفوظة', 
    en: 'All Rights Reserved' 
  },
  customOrders: { en: 'Custom Orders', ar: 'طلبات خاصة' },
  corporateTitle: { en: 'Design Cards for Your Team', ar: 'صمم كروت فريق العمل الخاص بك' },
  corporateDesc: { en: 'Special and unique cards with exclusive specifications to fit your brand identity.', ar: 'كروت خاصة ومميزة بمواصفات حصرية تناسب هويتك التجارية وفريق عملك.' },
  orderNow: { en: 'Request Custom Cards', ar: 'اطلب كروتك الخاصة الآن' },
  companyName: { en: 'Organization Name', ar: 'اسم الجهة / الشركة' },
  staffCount: { en: 'Number of Staff', ar: 'عدد الموظفين المتوقع' },
  messageSubject: { en: 'Additional Details', ar: 'تفاصيل إضافية عن الطلب' },
  submitRequest: { en: 'Send Request', ar: 'إرسال طلب التصميم' },
  requestSuccess: { en: 'Request sent successfully!', ar: 'تم إرسال طلبك بنجاح!' },
  featureSecurity: { en: 'Account Protection & Verification', ar: 'حماية وتوثيق الحساب' },
  featureCustomDesign: { en: 'Unique Design', ar: 'تصميم خاص وفريد' },
  featureDashboard: { en: 'Team Control', ar: 'لوحة تحكم للفريق' },
  invitationPrefix: { en: 'Invited by', ar: 'يتشرف' },
  invitationWelcome: { en: 'Welcomes you to', ar: 'بدعوتكم لحضور' },
  editTemplate: { en: 'Edit Template', ar: 'تعديل القالب' },
  saveTemplate: { en: 'Save Template', ar: 'حفظ القالب' },
  appearance: { en: 'Appearance', ar: 'المظهر' },
  color: { en: 'Color', ar: 'لون' },
  gradient: { en: 'Gradient', ar: 'تدرج' },
  image: { en: 'Image', ar: 'صورة' },
  upload: { en: 'Upload', ar: 'رفع' },
  header: { en: 'Header', ar: 'الترويسة' },
  avatar: { en: 'Avatar', ar: 'الصورة الشخصية' },
  positioning: { en: 'Positioning', ar: 'التموضع' },
  height: { en: 'Height', ar: 'الارتفاع' },
  size: { en: 'Size', ar: 'الحجم' },
  yOffset: { en: 'Y Offset', ar: 'الإزاحة الرأسية' },
  name: { en: 'Name', ar: 'الاسم' },
  buttons: { en: 'Buttons', ar: 'الأزرار' },
  socialLinks: { en: 'Socials', ar: 'التواصل' },
  classic: { en: 'Classic', ar: 'كلاسيك' },
  split: { en: 'Split', ar: 'منقسم' },
  overlay: { en: 'Overlay', ar: 'متداخل' },
  minimal: { en: 'Minimal', ar: 'بسيط' },
  circle: { en: 'Circle', ar: 'دائري' },
  squircle: { en: 'Squircle', ar: 'منحنٍ' },
  hidden: { en: 'Hidden', ar: 'إخفاء' },
  showQrCode: { en: 'Show QR Code', ar: 'إظهار رمز الـ QR' },
  socialIconColorType: { ar: 'نمط ألوان الأيقونات', en: 'Icon Color Style' },
  brandColors: { ar: 'الألوان الأصلية', en: 'Brand Colors' },
  designColors: { ar: 'ألوان التصميم', en: 'Design Colors' },
  addShortcut: { ar: 'اختصار للشاشة', en: 'Add Shortcut' },
  shortcutGuideTitle: { ar: 'إنشاء اختصار للبطاقة', en: 'Create Card Shortcut' },
  iosGuide: { ar: 'في متصفح Safari، اضغط على أيقونة المشاركة (المربع والسهم) ثم اختر "إضافة إلى الصفحة الرئيسية".', en: 'In Safari, tap the Share icon (square with arrow) and select "Add to Home Screen".' },
  androidGuide: { ar: 'في متصفح Chrome، اضغط على القائمة (⋮) في الأعلى ثم اختر "الإضافة إلى الشاشة الرئيسية".', en: 'In Chrome, tap the menu (⋮) at the top and select "Add to Home Screen".' },
  specialFeatures: { ar: 'المميزات الخاصة', en: 'Special Features' },
  premiumFeaturesDesc: { ar: 'ميزات استثنائية لتخصيص البطاقات بشكل احترافي (ميزات قادمة مدفوعة).', en: 'Exclusive features for professional card customization (Upcoming premium features).' },
  specialLinks: { ar: 'روابط صور (عروض/منتجات)', en: 'Image Links (Offers/Products)' },
  addSpecialLink: { ar: 'إضافة صورة ورابط', en: 'Add Image & Link' },
  specialLinkUrl: { ar: 'رابط الوجهة', en: 'Link URL' },
  specialLinksCols: { ar: 'عدد الأعمدة', en: 'Column Count' },
  directLinksSection: { ar: 'قسم الروابط المباشرة', en: 'Direct Links Section' },
  pills: { ar: 'أيقونات', en: 'Pills' },
  grid: { ar: 'شبكة', en: 'Grid' },
  list: { ar: 'قائمة', en: 'List' },
  linksShowText: { ar: 'إظهار النص مع الأيقونة', en: 'Show Text with Icon' },
  linksIconsOnly: { ar: 'أيقونات فقط', en: 'Icons Only' },
  linksShowBg: { ar: 'إظهار خلفية للقسم', en: 'Show Section Background' },
  addEmail: { ar: 'إضافة إيميل', en: 'Add Email' },
  addWebsite: { ar: 'إضافة موقع', en: 'Add Website' },
  manageLinks: { ar: 'إدارة روابط الصور', en: 'Manage Image Links' },
  selectSiteFont: { ar: 'خط الموقع الرئيسي', en: 'Primary Site Font' },
  elementsColorLab: { ar: 'مختبر ألوان العناصر', en: 'Elements Color Lab' },
  nameColor: { ar: 'لون الاسم', en: 'Name Color' },
  titleColor: { ar: 'لون المسمى والشركة', en: 'Title/Company Color' },
  bioColor: { ar: 'لون نص النبذة', en: 'Bio Text Color' },
  linksBtnColor: { ar: 'لون الروابط والأزرار', en: 'Links & Primary Buttons' },
  socialIconColor: { ar: 'لون أيقونات التواصل', en: 'Social Icons Color' },
  phoneBtnColor: { ar: 'لون زر الاتصال', en: 'Phone Button Color' },
  whatsappBtnColor: { ar: 'لون زر واتساب', en: 'WhatsApp Button Color' },
  membershipSection: { ar: 'العضويات والاشتراكات', en: 'Memberships & Subscriptions' },
  membershipTitle: { ar: 'عنوان العضوية', en: 'Membership Title' },
  startDate: { ar: 'تاريخ البدء', en: 'Start Date' },
  expiryDate: { ar: 'تاريخ الانتهاء', en: 'Expiry Date' },
  showMembership: { ar: 'إظهار قسم العضوية', en: 'Show Membership Section' },
  remainingDays: { ar: 'أيام متبقية', en: 'Days Remaining' },
  membershipStatus: { ar: 'حالة الاشتراك', en: 'Subscription Status' },
  occasionSection: { ar: 'قسم المناسبات', en: 'Occasions Section' },
  showOccasion: { ar: 'إظهار قسم المناسبة', en: 'Show Occasion Section' },
  occasionTitleAr: { ar: 'عنوان المناسبة (AR)', en: 'Occasion Title (AR)' },
  occasionTitleEn: { ar: 'عنوان المناسبة (EN)', en: 'Occasion Title (EN)' },
  occasionDate: { ar: 'تاريخ ووقت المناسبة', en: 'Occasion Date & Time' },
  accentColorTimer: { ar: 'اللون المميز (المؤقت)', en: 'Accent Color (Timer)' },
  occasionBgColor: { ar: 'لون خلفية القسم', en: 'Section Background Color' },
  glassyEffect: { ar: 'تأثير زجاجي شفاف', en: 'Glassy Effect' },
  unitDays: { ar: 'يوم', en: 'DAYS' },
  unitHours: { ar: 'ساعة', en: 'HRS' },
  unitMinutes: { ar: 'دقيقة', en: 'MIN' },
  unitSeconds: { ar: 'ثانية', en: 'SEC' },
  contactNumbers: { ar: 'أرقام التواصل', en: 'Direct Contact' },
  websiteLink: { ar: 'رابط الموقع الإلكتروني (إن وجد)', en: 'Website URL (if any)' },
  socialLink: { ar: 'رابط منصات التواصل (إنستقرام/لينكدإن)', en: 'Social Media Link (IG/LinkedIn)' },
  logoLabel: { ar: 'شعار الجهة / الشركة', en: 'Company Logo' },
  uploadAction: { ar: 'اختيار الشعار', en: 'Select Logo' },
  
  basicEditorTitle: { ar: 'المحرر الأساسي (مجاني)', en: 'Basic Editor (Free)' },
  advancedEditorTitle: { ar: 'المحرر المتقدم (احترافي)', en: 'Advanced Editor (Pro)' },
  basicEditorDesc: { ar: 'يمكنك تعديل بياناتك الشخصية فقط. التنسيقات البصرية ثابتة في هذا الوضع.', en: 'You can only edit personal data. Visual styling is fixed in this mode.' },
  advancedEditorDesc: { ar: 'تحكم كامل في الألوان، التنسيقات، الأبعاد، ونظام العضويات.', en: 'Full control over colors, layouts, dimensions, and membership systems.' },
  upgradeToCustomize: { ar: 'قم بالترقية لفتح أدوات التصميم', en: 'Upgrade to unlock design tools' }
};
